
smtp:
  server: smtp.server.com
  port: 465
  ssl: true
  username: smtp_username@domain.com
  password: smtp_password

send_targets:
  - name: YourName
    email: your_email@domain.com
    items:
      - put_links_here
